allowBuilds:
  esbuild: false
  lefthook: true
  msw: false
catalogMode: manual
engineStrict: true

minimumReleaseAge: 1440
overrides:
  '@mcpc-tech/acp-ai-provider>zod': 4.4.1
  serialize-javascript@<7.0.5: '>=7.0.5'
  uuid@<14.0.0: '>=14.0.0'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
saveExact: true

enableGlobalVirtualStore: true
