// @generated by native/scripts/generate-openapi-rust-client.mjs from docs/tmp/openapi.json
// Do not edit by hand.

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentPreset {
    pub id: String,
    pub label: String,
    pub description: String,
    pub command: String,
    pub args: Vec<String>,
    #[serde(rename = "modelSelectLabel")]
    pub model_select_label: Option<String>,
    #[serde(rename = "modeSelectLabel")]
    pub mode_select_label: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AppInfo {
    #[serde(rename = "appName")]
    pub app_name: String,
    #[serde(rename = "workingDirectory")]
    pub working_directory: String,
    #[serde(rename = "projectsFilePath")]
    pub projects_file_path: String,
    #[serde(rename = "agentPresets")]
    pub agent_presets: Vec<AgentPreset>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct Project {
    pub id: String,
    pub name: String,
    #[serde(rename = "workingDirectory")]
    pub working_directory: String,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ProjectsResponse {
    pub projects: Vec<Project>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ModeOption {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ModelOption {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct SlashCommand {
    pub name: String,
    pub description: String,
    #[serde(rename = "inputHint")]
    pub input_hint: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct SessionSummary {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    pub origin: String,
    pub status: String,
    #[serde(rename = "projectId")]
    pub project_id: Option<String>,
    #[serde(rename = "presetId")]
    pub preset_id: Option<String>,
    pub command: String,
    pub args: Vec<String>,
    pub cwd: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    pub title: Option<String>,
    #[serde(rename = "firstUserMessagePreview")]
    pub first_user_message_preview: Option<String>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<String>,
    #[serde(rename = "currentModeId")]
    pub current_mode_id: Option<String>,
    #[serde(rename = "currentModelId")]
    pub current_model_id: Option<String>,
    #[serde(rename = "availableModes")]
    pub available_modes: Vec<ModeOption>,
    #[serde(rename = "availableModels")]
    pub available_models: Vec<ModelOption>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct SessionsResponse {
    pub sessions: Vec<SessionSummary>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct RawEvent {
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(rename = "streamId")]
    pub stream_id: String,
    pub text: String,
    #[serde(rename = "rawText")]
    pub raw_text: String,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ChatMessage {
    pub id: String,
    pub role: String,
    pub kind: Option<String>,
    pub text: String,
    #[serde(rename = "rawEvents")]
    pub raw_events: Vec<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<String>,
    #[serde(rename = "streamPartId")]
    pub stream_part_id: Option<String>,
    #[serde(rename = "metadataJson")]
    pub metadata_json: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct SessionMessagesResponse {
    pub messages: Vec<ChatMessage>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct MessageRequest {
    pub prompt: String,
    #[serde(rename = "attachmentIds")]
    pub attachment_ids: Option<Vec<String>>,
    #[serde(rename = "modelId")]
    pub model_id: Option<String>,
    #[serde(rename = "modeId")]
    pub mode_id: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct CreateSessionRequest {
    #[serde(rename = "projectId")]
    pub project_id: Option<String>,
    #[serde(rename = "presetId")]
    pub preset_id: Option<String>,
    pub command: Option<String>,
    #[serde(rename = "argsText")]
    pub args_text: Option<String>,
    pub cwd: Option<String>,
    #[serde(rename = "modelId")]
    pub model_id: Option<String>,
    #[serde(rename = "modeId")]
    pub mode_id: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct PrepareSessionRequest {
    #[serde(rename = "projectId")]
    pub project_id: Option<String>,
    #[serde(rename = "presetId")]
    pub preset_id: String,
    pub cwd: Option<String>,
    #[serde(rename = "modelId")]
    pub model_id: Option<String>,
    #[serde(rename = "modeId")]
    pub mode_id: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct PrepareSessionResponse {
    #[serde(rename = "prepareId")]
    pub prepare_id: String,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct SessionResponse {
    pub session: SessionSummary,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct MessageResponse {
    pub session: SessionSummary,
    pub text: String,
    #[serde(rename = "rawEvents")]
    pub raw_events: Vec<serde_json::Value>,
    #[serde(rename = "assistantSegmentMessages")]
    pub assistant_segment_messages: Option<Vec<serde_json::Value>>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ProviderEntry {
    pub preset: AgentPreset,
    pub enabled: bool,
    #[serde(rename = "enabledAt")]
    pub enabled_at: Option<String>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentProvidersResponse {
    pub providers: Vec<ProviderEntry>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentModelCatalogResponse {
    #[serde(rename = "availableModels")]
    pub available_models: Vec<ModelOption>,
    #[serde(rename = "availableModes")]
    pub available_modes: Vec<ModeOption>,
    #[serde(rename = "currentModelId")]
    pub current_model_id: Option<String>,
    #[serde(rename = "currentModeId")]
    pub current_mode_id: Option<String>,
    #[serde(rename = "lastError")]
    pub last_error: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentSlashCommandsResponse {
    pub commands: Vec<SlashCommand>,
    #[serde(rename = "lastError")]
    pub last_error: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ProjectModelPreference {
    #[serde(rename = "presetId")]
    pub preset_id: String,
    #[serde(rename = "modelId")]
    pub model_id: String,
    #[serde(rename = "isFavorite")]
    pub is_favorite: bool,
    #[serde(rename = "lastUsedAt")]
    pub last_used_at: Option<String>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ProjectSettings {
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "modelPreferences")]
    pub model_preferences: Vec<ProjectModelPreference>,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ProjectSettingsResponse {
    pub settings: ProjectSettings,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct ErrorResponse {
    pub error: String,
}
