import inquirer from 'inquirer';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createCliProgram, type ServeOptions } from './cli-program.pure.ts';
import {
  applyServeEnvOverrides,
  resolveModePort,
  validateServeOptions,
} from './serve-options.pure.ts';
import { parseTcpPort } from './tailscale.pure.ts';

const generateApiKey = (): string => {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Buffer.from(bytes).toString('base64url');
};

const confirmPrompt = async (
  message: string,
  options?: { readonly defaultValue?: boolean },
): Promise<boolean> => {
  const { confirmed } = await inquirer.prompt<{
    readonly confirmed: boolean;
  }>([
    {
      type: 'confirm',
      name: 'confirmed',
      default: options?.defaultValue ?? true,
      message,
    },
  ]);
  return confirmed;
};

const logCheck = (message: string): void => {
  console.log(`✅ ${message}`);
};

const serve = async (options: ServeOptions): Promise<void> => {
  validateServeOptions(options);
  applyServeEnvOverrides(process.env, options);
  const { envService } = await import('../server/env.ts');
  const cliDirectory = path.dirname(fileURLToPath(import.meta.url));
  const clientBuildDirectory = path.resolve(cliDirectory, 'client');

  if (options.sameLan !== undefined) {
    const sameLanPort = parseTcpPort(
      resolveModePort({
        port: options.port,
        defaultPort: envService.getEnv('PORT'),
      }),
      '--port',
    );
    const confirmed = await confirmPrompt(
      [
        'WARNING: --same-lan exposes remote-agent to devices on the same LAN/Wi-Fi.',
        'Do not use this on public or untrusted Wi-Fi unless you understand the risk.',
        'If RA_API_KEY is not set, API requests are unauthenticated.',
        `remote-agent will listen on 0.0.0.0:${sameLanPort}. Continue?`,
      ].join('\n'),
      { defaultValue: false },
    );
    if (!confirmed) {
      console.log('Canceled. Same-LAN access was not started.');
      return;
    }

    const {
      createSameLanHttpsCredentials,
      ensureSameLanCertificateAuthority,
      getLanIPv4Candidates,
      getLocalHostname,
      installSameLanCertificateAuthorityForCurrentUser,
      isSameLanCertificateAuthorityTrustedForCurrentUser,
      printSameLanAccessInfo,
      startSameLanMdnsAdvertisement,
    } = await import('./same-lan.ts');
    const candidates = getLanIPv4Candidates();
    const localHostname = getLocalHostname();
    const certificateAuthority = await ensureSameLanCertificateAuthority(
      envService.getEnv('RA_DIR'),
      localHostname,
    );
    const isPcCertificateTrusted =
      await isSameLanCertificateAuthorityTrustedForCurrentUser(certificateAuthority);
    if (isPcCertificateTrusted) {
      logCheck('local CA certificate is already trusted on this PC');
    } else {
      const shouldInstallPcCertificate = await confirmPrompt(
        [
          'Install the remote-agent local CA certificate on this PC?',
          'This helps the PC browser trust same-LAN HTTPS URLs generated by remote-agent.',
        ].join('\n'),
        { defaultValue: true },
      );
      if (shouldInstallPcCertificate) {
        try {
          await installSameLanCertificateAuthorityForCurrentUser(certificateAuthority);
          logCheck('local CA certificate installed on this PC');
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          console.warn(`Failed to install local CA certificate on this PC: ${message}`);
          console.warn(`You can install it manually from: ${certificateAuthority.certPath}`);
        }
      }
    }

    const https = await createSameLanHttpsCredentials({
      localHostname,
      lanAddresses: candidates,
      certificateAuthority,
    });
    const mdnsAdvertisement = startSameLanMdnsAdvertisement({
      port: sameLanPort,
      localHostname,
    });
    const selectedAddress = candidates[0]?.address;
    const appUrl =
      localHostname === null
        ? `https://${selectedAddress ?? 'localhost'}:${sameLanPort}`
        : `https://${localHostname}.local:${sameLanPort}`;
    const limitedAppUrl =
      selectedAddress === undefined
        ? `http://localhost:${sameLanPort}`
        : `http://${selectedAddress}:${sameLanPort}`;
    const certificateUrl = `${limitedAppUrl}/.well-known/remote-agent-local-ca.crt`;
    const { startServer } = await import('../server/server.ts');
    const runningServer = startServer({
      port: sameLanPort,
      hostname: '0.0.0.0',
      https,
      clientBuildDirectory: options.serverOnly === true ? undefined : clientBuildDirectory,
      trustedCertificate: {
        certificatePem: certificateAuthority.cert,
        fileName: 'remote-agent-local-ca.crt',
      },
      mobileSetup: {
        appUrl,
        limitedAppUrl,
        certificateUrl,
      },
      allowHttpCertificateBootstrap: true,
    });
    let isSameLanCleanedUp = false;
    const cleanUpSameLan = (): void => {
      if (isSameLanCleanedUp) {
        return;
      }
      isSameLanCleanedUp = true;
      mdnsAdvertisement.cleanUp();
      runningServer.cleanUp();
    };
    const handleSameLanSignal = (): void => {
      cleanUpSameLan();
      process.exit(0);
    };
    process.once('SIGINT', handleSameLanSignal);
    process.once('SIGTERM', handleSameLanSignal);
    await printSameLanAccessInfo({
      port: sameLanPort,
      protocol: 'https',
      localHostname,
      candidates,
      mdnsAdvertisement,
      certificateAuthority,
    });
    return;
  }

  const { startServer } = await import('../server/server.ts');
  const parsedLocalPort =
    options.port === undefined ? undefined : parseTcpPort(options.port, '--port');

  if (options.tailscale === undefined) {
    startServer({
      port: parsedLocalPort ?? envService.getEnv('PORT'),
      clientBuildDirectory: options.serverOnly === true ? undefined : clientBuildDirectory,
    });
    return;
  }

  const tailscalePort = parseTcpPort(
    resolveModePort({
      port: options.port,
      defaultPort: envService.getEnv('PORT'),
    }),
    '--port',
  );
  const publicPort = tailscalePort;
  const localPort = tailscalePort;
  const {
    ensureTailscaleCommandAvailable,
    readTailscaleStatus,
    renderTerminalQrCode,
    runTailscaleUp,
    startTailscaleServe,
    stopTailscaleServe,
  } = await import('./tailscale.ts');
  await ensureTailscaleCommandAvailable();
  logCheck('tailscale cli is installed');

  let tailscaleStatus = await readTailscaleStatus().catch(() => null);
  const shouldRunTailscaleUp =
    tailscaleStatus === null ||
    tailscaleStatus.BackendState !== 'Running' ||
    tailscaleStatus.HaveNodeKey !== true;

  if (shouldRunTailscaleUp) {
    const confirmed = await confirmPrompt(
      [
        'Tailscale is not ready for remote-agent.',
        'Run `tailscale up` now? If that fails, remote-agent will retry with sudo.',
      ].join('\n'),
    );
    if (!confirmed) {
      console.log('Canceled. Tailscale was not changed.');
      return;
    }
    await runTailscaleUp();
    tailscaleStatus = await readTailscaleStatus();
    logCheck('tailscale up completed');
  }

  logCheck('tailscale backend is running');
  logCheck('tailscale node key is available');

  const dnsName = tailscaleStatus?.Self?.DNSName?.trim();
  if (
    tailscaleStatus?.CurrentTailnet?.MagicDNSEnabled === false ||
    dnsName === undefined ||
    dnsName.length === 0
  ) {
    throw new Error(
      [
        'Tailscale MagicDNS is not ready.',
        'Enable MagicDNS in the Tailscale admin console, then rerun this command:',
        '  https://login.tailscale.com/admin/dns',
      ].join('\n'),
    );
  }
  logCheck('tailscale MagicDNS is enabled');
  const normalizedDnsName = dnsName.replace(/\.$/, '');
  logCheck(`tailscale DNS name is ${normalizedDnsName}`);

  const shouldConfigureTailscale = await confirmPrompt(
    [
      'Configure Tailscale Serve for remote-agent?',
      `This will run: tailscale serve --bg --https=${publicPort} http://127.0.0.1:${localPort}`,
    ].join('\n'),
  );

  if (!shouldConfigureTailscale) {
    console.log('Canceled. Tailscale Serve was not changed.');
    return;
  }

  const runningServer = startServer({
    port: localPort,
    hostname: '127.0.0.1',
    clientBuildDirectory: options.serverOnly === true ? undefined : clientBuildDirectory,
  });

  try {
    const { publicUrl } = await startTailscaleServe({ publicPort, localPort });
    const qrCode = await renderTerminalQrCode(publicUrl);

    console.log('');
    console.log('Tailscale connection ready');
    console.log(`  Local:     http://127.0.0.1:${localPort}`);
    console.log(`  Tailscale: ${publicUrl}`);
    console.log('');
    console.log('Open from another device in your tailnet:');
    console.log(`  ${publicUrl}`);
    console.log('');
    console.log(qrCode);

    const cleanUp = async (): Promise<void> => {
      console.log('');
      console.log('Cleaning up remote-agent...');
      runningServer.cleanUp();
      console.log('✅ remote-agent server stopped');
      try {
        await stopTailscaleServe(publicPort);
        console.log(`✅ tailscale serve --https=${publicPort} stopped`);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.warn(`Failed to stop Tailscale Serve: ${message}`);
      }
    };

    const handleSignal = (_signal: NodeJS.Signals): void => {
      void cleanUp().finally(() => {
        process.exit(0);
      });
    };

    process.once('SIGINT', handleSignal);
    process.once('SIGTERM', handleSignal);
  } catch (error) {
    runningServer.cleanUp();
    try {
      await stopTailscaleServe(publicPort);
    } catch {
      // Ignore cleanup failures after a failed setup; the original setup error is more useful.
    }
    throw error;
  }
};

await createCliProgram({ generateApiKey, serve }).parseAsync();
