/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProjectsRouteImport } from "./routes/projects";
import { Route as DebugRouteImport } from "./routes/debug";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectsIndexRouteImport } from "./routes/projects.index";
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects.$projectId";

const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const DebugRoute = DebugRouteImport.update({
  id: "/debug",
  path: "/debug",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProjectsRoute,
} as any);
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/$projectId",
  path: "/$projectId",
  getParentRoute: () => ProjectsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/debug": typeof DebugRoute;
  "/projects": typeof ProjectsRouteWithChildren;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/projects/": typeof ProjectsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/debug": typeof DebugRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/projects": typeof ProjectsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/debug": typeof DebugRoute;
  "/projects": typeof ProjectsRouteWithChildren;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/projects/": typeof ProjectsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/debug" | "/projects" | "/projects/$projectId" | "/projects/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/debug" | "/projects/$projectId" | "/projects";
  id: "__root__" | "/" | "/debug" | "/projects" | "/projects/$projectId" | "/projects/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DebugRoute: typeof DebugRoute;
  ProjectsRoute: typeof ProjectsRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof ProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/debug": {
      id: "/debug";
      path: "/debug";
      fullPath: "/debug";
      preLoaderRoute: typeof DebugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/": {
      id: "/projects/";
      path: "/";
      fullPath: "/projects/";
      preLoaderRoute: typeof ProjectsIndexRouteImport;
      parentRoute: typeof ProjectsRoute;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof ProjectsProjectIdRouteImport;
      parentRoute: typeof ProjectsRoute;
    };
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
};

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(ProjectsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
